Products.Web/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;

namespace Products.Web.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }
    }
}

Products.Web/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using Products.Web.Areas.HelpPage.Models;

namespace Products.Web.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View("Error");
        }
    }
}

Products.Web/Controllers/CategoryController.cs
using Products.Library;
using Products.Library.ProductsRepository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace Products.Web.Controllers
{
    public class CategoryController : ApiController
    {
        private CategoriesRepository categoriesRepository;

        //Constructor
        public CategoryController()
        {
            this.categoriesRepository = new CategoriesRepository();
        }

        // api/categories
        public List<Category> GetAll()
        {
            var CategoriesList = categoriesRepository.GetAllCategories();
            return CategoriesList;
        }

    }
}

Products.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Products.Web.Controllers
{
    public class HomeController : Controller
    {
        //MVC Controller
        public ActionResult Index()
        {
            return View();
        }
    }
}

Products.Web/Controllers/ProductsController.cs
using Products.Library;
using Products.Library.ProductsRepository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace Products.Web.Controllers
{
    public class ProductsController : ApiController
    {

        private ProductsRepository productRepository;

        //Constructor
        public ProductsController()
        {
            this.productRepository = new ProductsRepository();
        }


        //api/products
       // [Authorize(Users = "bill")]
        public List<Product> GetAll()
        {
            var productList = productRepository.GetAllProducts();
            return productList;
        }

        //api/product/id
        //route settings e.g., api/products/1234 or use api/products?id=1234
        // routeTemplate: "api/{controller}/{id}",
        public Product GetById(int productId)
        {
            var product = productRepository.GetProductById(productId);
            if (product == null)
            {
                throw new HttpResponseException(HttpStatusCode.NotFound);
            }

            return product;
        }


        //api/products?cat=electronics
        public List<Product> GetProductsCategory(string cat)
        {
            var products = productRepository.GetProductsByCategory(cat).ToList();
            return products;
        }

        //POST for Create  // api/products 
        public HttpResponseMessage PostProduct(Product prod)
        {
            Product p = productRepository.Add(prod);
            if(prod!=null)
            {
                var response = Request.CreateResponse<Product>(HttpStatusCode.Created, prod);
                string uri = Url.Link("DefaultApi", new { id=prod.ProductName});
                response.Headers.Location = new Uri(uri);
                return response;
            }
            else
                throw new HttpResponseException(HttpStatusCode.InternalServerError);            
        }

        //PUT FOR UPDATE // api/products/id 
        public void PutProduct(Product prod)
        {
            var res = productRepository.Update(prod);
            if(res==null)
            {
                throw new HttpResponseException(HttpStatusCode.NotFound);
            }
        }


        // DELETE api/Book/5
        public HttpResponseMessage DeleteProduct(int productId)
        {
            Product product = productRepository.GetProductById(productId);
            if (product == null)
            {
                return Request.CreateResponse(HttpStatusCode.NotFound);
            }
            productRepository.Delete(productId);
            return Request.CreateResponse(HttpStatusCode.OK, product);
        }

    }
}

Products.Web/Controllers/ValuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace Products.Web.Controllers
{
    public class ValuesController : ApiController
    {
        // GET api/values
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/values/5
        public string Get(int id)
        {
            return "value";
        }

        // POST api/values
        public void Post([FromBody]string value)
        {
        }

        // PUT api/values/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/values/5
        public void Delete(int id)
        {
        }
    }
}

Products.Web/Views/Home/Index.cshtml
<div id="body">
    <section class="content-wrapper main-content clear-fix">
        <div>
            <h2>All Products</h2>
            <ul id="products" />
        </div>
        <div>
            <h2>Search by ID</h2>
            <input type="text" id="prodId" size="5" />
            <input type="button" value="Search" onclick="find();" />
            <p id="product" />
        </div>
        <div>
            <h2>Get Products By Category</h2>
            <input type="text" id="cat" size="15" />
            <input type="button" value="Get Products By category" onclick="getProductsByCategory();" />
            <p id="catproducts" />
        </div>

    </section>
</div>

@section scripts {
    <script>
    var apiUrl = 'api/products';
    $(document).ready(function () {
        // Send an AJAX request
        $.getJSON(apiUrl)
            .done(function (data) {
                // On success, 'data' contains a list of products.
                $.each(data, function (key, item) {
                    // Add a list item for the product.
                    var str = item.ProductId + '  ' + item.ProductName + ': $' + item.Price + "  " + item.CategoryName + item.UnitInStock;
                    $('<li>', { text: str }).appendTo($('#products'));
                });
            });
    });


    function find() {
        var id = $('#prodId').val();
        $.getJSON(apiUrl + '/' + id)
            .done(function (data) {
                var str = data.ProductId + '  ' + data.ProductName + ': $' + data.Price + "  " + data.CategoryName + data.UnitInStock;
                $('#product').text(str);
            })
            .fail(function (jqXHR, textStatus, err) {
                $('#product').text('Error: ' + err);
            });
    }

    function getProductsByCategory() {
        var category = $('#cat').val();
        var str = '';
        $.getJSON(apiUrl + '?cat=' + category)
         .done(function (data) {
             $.each(data, function (key, item) {
                 // Add a list item for the product.
                 str += item.ProductId + '  ' + item.ProductName + ': $' + item.Price + "  " + item.CategoryName + item.UnitInStock + '<br/>';
             });
             $('#catproducts').html(str);
         });
    }
    </script>
}

Products.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">
                    <a href="~/">ASP.NET Web API</a></p>
            </div>
            <div class="float-right">
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>