Products.Client/Controllers/ProductRestController.cs
using Products.Library;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RestSharp.Authenticators;
using PagedList;


namespace Products.Client.Controllers
{
    
    public class ProductRestController : Controller
    {
        //TODO:Move to configuration
        private const string localUrl = "http://localhost:56539/";
        //Basic Authentication
        private const string userName = "bill";
        private const string passWord = "bill";

        ProductClient _productClient = new ProductClient(localUrl, userName, passWord);       
     
        // GET: /ProductRest/ 
       // [Authorize(Roles="A")]
        [Authorize]
        public ActionResult Index(string sortOrder,string currentFilter,string searchString,int?page)      
        {
            ViewBag.CurrentSort = sortOrder;
            //Decending the list by ProductName
            ViewBag.NameSort = String.IsNullOrEmpty(sortOrder) ? "ProductName_desc" : "";
            //Decending the list by the Price
            ViewBag.PriceSort = sortOrder == "Price" ? "Price_desc" : "Price";
             
            if(searchString!=null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            var products = _productClient.GetAll().ToList();
            //Search the string if it is included in the ProductName
            if(!String.IsNullOrEmpty(searchString))
            {
                products = products.Where(x => x.ProductName.Contains(searchString)).ToList();
            }
            switch(sortOrder)
            {
                //Decending by the Product Name:
                case "ProductName_desc":
                    products = products.OrderByDescending(x => x.ProductName).ToList();
                    break;
                //Oder By the Price
                case "Price":
                    products = products.OrderBy(x => x.Price).ToList();
                    break;
                //Decending by the Product Price:
                case "Price_desc":
                    products = products.OrderByDescending(x => x.Price).ToList();
                    break;
                default://Id acsending
                    products = products.OrderBy(x => x.ProductId).ToList();
                    break;
            }
            //Paging:
            int pageSize = 5;
            int pageNumber = (page ?? 1);           
           
            return View(products.ToPagedList(pageNumber,pageSize));
        }

        public ActionResult Create()
        {
            return View();
        }


        //Post for create
        [HttpPost]
        public ActionResult Create(FormCollection fields, Product product)
        {
            //
            product.ProductName = fields["ProductName"];
            product.CategoryName = fields["Category"];
            product.Price = Convert.ToDecimal(fields["Price"]);
            product.UnitInStock = Convert.ToInt16(fields["UnitInStock"]);

            product = _productClient.CreateProduct(product);
            return RedirectToAction("Index");
        }


        //Get: Product/Update/1
        //GetProduct
        public ActionResult Update(int productId)
        {
            var product = _productClient.GetProduct(productId);
            return View(product);
        }


        //Put:Product/Update/1
          [HttpPost]
        public ActionResult Update(FormCollection fields, Product product)
          {
              product.ProductName = fields["ProductName"];
              product.CategoryName = fields["Category"];
              product.Price = Convert.ToDecimal(fields["Price"]);
              product.UnitInStock = Convert.ToInt16(fields["UnitInStock"]);
              product = _productClient.PutProduct(product);
              return RedirectToAction("Index");
          }

          // GET: Blogs/Delete/5
          public ActionResult Delete(int productId)
          {              
              Product prod = _productClient.GetProduct(productId);              
              if (prod == null)
              {
                  return HttpNotFound();
              }
              return View(prod);
          }


          // Delete: Blogs/Delete/5          
          public ActionResult DeleteConfirmed(int ProductId)
          {
              _productClient.DeleteProduct(ProductId);
              return RedirectToAction("Index");
          }

    }
}

Products.Client/Controllers/ProductsController.cs
using Products.Library;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Formatting;
using System.Net.Http.Headers;
using System.Text;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace Products.Client.Controllers
{
     [Authorize]
    public class ProductsController : Controller
    {
        //
        // GET: /Products/
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)   
        {
           // HttpClient client = new HttpClient();
            //client.BaseAddress = new Uri("http://localhost:56539/");
            HttpClientHandler handler = new HttpClientHandler();
            //handler.Credentials = new NetworkCredential("billy", "bill100");

            HttpClient client = new HttpClient(handler);
            client.DefaultRequestHeaders.Authorization =
                    new System.Net.Http.Headers.AuthenticationHeaderValue("basic",
                        Convert.ToBase64String(ASCIIEncoding.ASCII.GetBytes("bill:bill")));
            client.BaseAddress = new Uri("http://localhost:56539/");

            // Add an Accept header for JSON format.
            client.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/json"));

            // get all products
            HttpResponseMessage response = client.GetAsync("api/products").Result;
            if (response.IsSuccessStatusCode)
            {
                int pageSize = 5;
                int pageNumber = (page ?? 1);
                // Parse the response body
                var products = response.Content.ReadAsAsync<List<Product>>().Result.ToList();
                //Search and Sort
                ViewBag.CurrentSort = sortOrder;
                //Decending the list by ProductName
                ViewBag.NameSort = String.IsNullOrEmpty(sortOrder) ? "ProductName_desc" : "";
                //Decending the list by the Price
                ViewBag.PriceSort = sortOrder == "Price" ? "Price_desc" : "Price";

                if (searchString != null)
                {
                    page = 1;
                }
                else
                {
                    searchString = currentFilter;
                }
                ViewBag.CurrentFilter = searchString;
                
                //Search the string if it is included in the ProductName
                if (!String.IsNullOrEmpty(searchString))
                {
                    products = products.Where(x => x.ProductName.Contains(searchString)).ToList();
                }
                switch (sortOrder)
                {
                    //Decending by the Product Name:
                    case "ProductName_desc":
                        products = products.OrderByDescending(x => x.ProductName).ToList();
                        break;
                    //Oder By the Price
                    case "Price":
                        products = products.OrderBy(x => x.Price).ToList();
                        break;
                    //Decending by the Product Price:
                    case "Price_desc":
                        products = products.OrderByDescending(x => x.Price).ToList();
                        break;
                    default://Id acsending
                        products = products.OrderBy(x => x.ProductId).ToList();
                        break;
                }
                return View(products.ToPagedList(pageNumber, pageSize));
            }
            else
            {
                throw new InvalidDataException(string.Format("{0} ({1})", response.StatusCode, response.ReasonPhrase));
            }
        }



        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(FormCollection fields, Product product)
        {
            product.ProductName = fields["ProductName"];
            product.CategoryName = fields["Category"];
            product.Price = Convert.ToDecimal(fields["Price"]);
            product.UnitInStock = Convert.ToInt16(fields["UnitInStock"]);

            //call webApi to add new product
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:56539/");
            // Add an Accept header for JSON format.
            client.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/json"));

            // add new  product  - post returns the created resource
            string apiurl = "api/products";
            HttpResponseMessage response = client.PostAsync<Product>(apiurl, product, new JsonMediaTypeFormatter()).Result;

            if (response.IsSuccessStatusCode)  // returns status 201 - created
            {
                //var products = response.Content.ReadAsAsync<IEnumerable<Product>>().Result;
                TempData["Product"] = String.Concat(" Product created successfully.." +
                    "with productId of " + product.ProductName.ToString());
            }
            else
            {
                TempData["Product"] = String.Concat(string.Format("{0} ({1})", response.StatusCode, response.ReasonPhrase));
            }
            return RedirectToAction("Index");
        }


        //Get: Product/Update/1
        public ActionResult Update(int productId)
        {
            Product product = new Product();
            //call webApi to add new product
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:56539/");
            // Add an Accept header for JSON format.
            client.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/json"));

            //Get:Product/1 
            string apiurl = "api/products" + "/" + productId;
            HttpResponseMessage response = client.GetAsync(apiurl).Result;
            if (response.IsSuccessStatusCode)  // returns status 201 - created
            {
                // Parse the response body
                product = response.Content.ReadAsAsync<Product>().Result;
                return View(product);
            }
            else
            {
                throw new InvalidDataException(string.Format("{0} ({1})", response.StatusCode, response.ReasonPhrase));
            }

        }


        //Put:Product/Update/1
        [HttpPost]
        public ActionResult Update(FormCollection fields, Product product)
        {
            product.ProductName = fields["ProductName"];
            product.CategoryName = fields["Category"];
            product.Price = Convert.ToDecimal(fields["Price"]);
            product.UnitInStock = Convert.ToInt16(fields["UnitInStock"]);

            //call webApi to add new product
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:56539/");
            // Add an Accept header for JSON format.
            client.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/json"));

            // update product  - update does not return anything in webapi
            string apiurl = "api/products" +"/"+ product.ProductId.ToString();
            //Put
            HttpResponseMessage response = client.PutAsync<Product>(apiurl, product, new JsonMediaTypeFormatter()).Result;
            return RedirectToAction("Index");
        }

        // GET: Blogs/Delete/5
        public ActionResult Deleted(int ProductId)
        {

            // HttpClient client = new HttpClient();
            //client.BaseAddress = new Uri("http://localhost:56539/");
            HttpClientHandler handler = new HttpClientHandler();
            //handler.Credentials = new NetworkCredential("billy", "bill100");

            HttpClient client = new HttpClient(handler);
            client.DefaultRequestHeaders.Authorization =
                    new System.Net.Http.Headers.AuthenticationHeaderValue("basic",
                        Convert.ToBase64String(ASCIIEncoding.ASCII.GetBytes("bill:bill")));
            client.BaseAddress = new Uri("http://localhost:56539/");



            // Add an Accept header for JSON format.
            client.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/json"));

            // get product/id
            string apiurl = "api/products" + "/" + ProductId;
            HttpResponseMessage response = client.GetAsync(apiurl).Result;
            if (response.IsSuccessStatusCode)
            {
                // Parse the response body
                var products = response.Content.ReadAsAsync<List<Product>>().Result.ToList();
                return View(products);
            }
            else
            {
                throw new InvalidDataException(string.Format("{0} ({1})", response.StatusCode, response.ReasonPhrase));
            }
        }

       

      
        public ActionResult Delete(int productId)
        {
            //call webApi to add new product
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:56539/");
            // Add an Accept header for JSON format.
            client.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/json"));

            // delete product  - delete does not return anything in webapi
            string apiurl = "api/products" + "/" + productId;
            HttpResponseMessage response = client.DeleteAsync(apiurl).Result;

            return RedirectToAction("Index");
        }
    }
}

Products.Client/Views/Products/Create.cshtml
@{
    ViewBag.Title = "Submit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="body">
    <h2>Product</h2>
    <form id="product" method="post" action="@Url.Action("Create")">
        <div class="form-group">
            <label for="ProductName">Product Name:</label>
            <input data-val="true" data-val-required="Please Fill the Product Name." type="text" name="ProductName" id="ProductName" />
            <span class="field-validation-valid" data-valmsg-for="ProductName" data-valmsg-replace="true"></span>
        </div>
        <div class="form-group">
            <label for="Category">Category:</label>
            <input data-val="true" data-val-required="Please Fill the Category Name." type="text" name="Category" id="Category" />
            <span class="field-validation-valid" data-valmsg-for="Category" data-valmsg-replace="true"></span>
        </div>
        <div class="form-group">
            <label for="Price">Price:</label>
            <input data-val="true" data-val-required="Please Fill the Price." type="text" name="Price" id="Price" />
            <span class="field-validation-valid" data-valmsg-for="Price" data-valmsg-replace="true"></span>
        </div>
        <div class="form-group">
            <label for="UnitInStock">UnitInStock:</label>
            <input data-val="true" data-val-required="Please Fill the Unit In Stock" type="text" name="UnitInStock" id="UnitInStock" />
            <span class="field-validation-valid" data-valmsg-for="UnitInStock" data-valmsg-replace="true"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Create" />
        </div>
    </form>
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Products.Client/Views/Products/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
<h3>Are you sure you want to delete this?</h3>
<div class="container">

    <div>
        Product Name:@Model.ProductName
    </div>
    <div>
        Category:@Model.CategoryName
    </div>
    <div>
        Price:@Model.Price
    </div>
    <div>
        UnitInStock:@Model.UnitInStock
    </div>
    <div>
        <a href="@Url.Action("Delete", new { ProductId = @Model.ProductId})">Delete</a>
        @Html.ActionLink("Back to List", "Index")
    </div>

</div>

Products.Client/Views/Products/Index.cshtml
@using PagedList.Mvc;
@using PagedList;
<link href="~/Content/PagedList.css" rel="stylesheet" />
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<div class="container">
    <h2>Product</h2>  
    @using (Html.BeginForm("Index", "ProductRest", FormMethod.Get))
    {
        <p>
            Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
            <input type="submit" value="Search" />
        </p>
    }  
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Product Id</th>
                <th>@Html.ActionLink("ProductName", "Index", new { sortOrder = ViewBag.NameSort})</th>
                <th>Category</th>
               <th>@Html.ActionLink("Price", "Index", new { sortOrder = ViewBag.PriceSort})</th>
                <th>UnitInStock</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var p in Model)
            {
                <tr>
                    <td>@p.ProductId</td>
                    <td>@p.ProductName</td>
                    <td>@p.CategoryName</td>
                    <td>@p.Price</td>
                    <td>@p.UnitInStock</td>
                    <td>@Html.ActionLink("Edit", "Update", new { ProductId = p.ProductId })</td>
                    <td>@Html.ActionLink("Delete", "Delete", new { ProductId = p.ProductId })</td>
                </tr>
            }
            @Html.ActionLink("Create New", "Create")            
    </tbody>
    </table>
    Page@(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }))
</div> 

@* 
<div>
    <h1>Test</h1>
    @{
        int i;
        List<int> odd = new List<int>();
        List<int> even = new List<int>();
        for (i = 1; i <= 100; i++)
        {
            if (i % 2 == 0)
            {
                even.Add(i);

            }
            else
            {
                odd.Add(i);

            }
        }
        foreach (int e in even)
        {
            <h3>@e</h3>
        }

        foreach (int e in odd)
        {
            <h3>@e</h3>
        }
}
</div>    *@      
      

Products.Client/Views/Products/Update.cshtml
<h2>Update</h2>
<div class="container">
    <form id="update" name="update" method="post" action="@Url.Action("Update")">
        <div class="form-group">
            <input type="hidden" value="@Model.ProductId" name="ProductId" />
            <label for="ProductName">Product Name:</label>
            <input type="text" name="ProductName" id="ProductName" value="@Model.ProductName" />
        </div>
        <div class="form-group">
            <label for="Category">Category:</label>
            <input type="text" name="Category" id="Category" value="@Model.CategoryName" />
        </div>
        <div class="form-group">
            <label for="Price">Price:</label>
            <input type="text" name="Price" id="Price" value="@Model.Price" />
        </div>
        <div class="form-group">
            <label for="Price">UnitInStock:</label>
            <input type="text" name="UnitInStock" id="UnitInStock" value="@Model.UnitInStock" />
        </div>       
        <div class="form-group">
            <input type="submit" value="Submit" />
        </div>
    </form>
</div>